### ISSUE TITLE
Logo is the same as Benthos

### ISSUE THREAD

**Issue by ethack** [linka-app/linka#26]
I'm guessing you know Linka's logo is the same as Benthos's. I'm creating this issue just in case you found the logo through other means and didn't know.

![benthos logo](https://raw.githubusercontent.com/benthosdev/benthos/main/icon.png)

- https://www.benthos.dev/
- https://github.com/benthosdev/benthos
- https://github.com/benthosdev/benthos/blob/main/icon.png

I'm guessing it's fine legal-wise (though I don't know) since Benthos is open source under MIT. Though larger open source projects will trademark their logos to protect how they can be used (e.g. Wireguard, Mozilla) and avoid brand confusion. I don't know if that's the case here, but you may still want to consider changing your logo to avoid any confusion if you intend to grow your project beyond something small/niche.

**Comment by cmsax** [comment]
Hi ethack, thanks for reminding this. Yes, the logo was just copied from Benthos and there's no any credit info about the original repo. I apologize for this confusing behavior. 🥵

To fix this issue, I'll regenerate another logo for this project.

**Comment by cmsax** [comment]
The icon was brought into this project in this [commit](https://github.com/linka-app/linka/commit/2521264d1e6cbb166066d1d3ad42908daf7c356a).
